### ISSUE TITLE
rom 48k sms

### ISSUE THREAD

**Issue by darleiv** [raphnet/flashrwSMS#1]
could tell why the master system does not start 48k rom. only 32k without using mapper?

**Comment by raphnet** [comment]
There could be many reasons for this. Bad 48k ROM. Bad wiring, bad mapper, incompatible or inappropriate mapper for the game in question... Also, a ROM without a checksum (for instance, a Japanese game) will not boot on non-Japanese systems with the original BIOS, etc.

I'm sorry but I don't see how this is an issue on this git repository. If you need help for development or engineering for the SMS, please use the smspower.org forums.

**Comment by darleiv** [comment]
I ASKED HERE BECAUSE I SAW YOUR 32K SMS BOARD AD. AND YOU SAY IT RUN UP TO 64K WITHOUT MAPPER. BUT MASTER SYSTEM DOES NOT ACCEPT ROM ABOVE 32K WITHOUT MAPPER. wire mo-7 + oe = run 32K ROM

**Comment by raphnet** [comment]
I'm sorry, I do not have a "32K SMS BOARD", what are you referring to precisely? My only SMS board available for sale is a 4MBIT (512 kilobytes) board with a mapper. This git repository is C code for the SMS which allows writing to the flash chip in this design: https://www.raphnet-tech.com/products/sms_4Megabit_cartridge_pcb/index.php

Were you perhaps trying to point out an error or ambiguity somewhere in my documentation? Could you provide a link to the page in question and an exact citation of my words so I can find them easily? I will be glad to rephrase if something is wrong.

Of course, wiring a ROM as you describe (using only MO_7) results in only 32k of ROM being accessible. If you really want to use a 48k ROM without a mapper, you would need to combine MO_7 and M8_B using an AND gate and send the output to the ROM (so the CE pin sees a low level from 0000 to BFFF. For this to work on non-Japanese machines (due to the BIOS) the ROM should have a checksum and the header should declare its size being 32k (you still program 48k of data - you just let the head say otherwise), since the BIOS will otherwise try to use the mapper while validating the checksum and it will fail. Besides, 48k ROM support is documented as buggy here:
https://www.smspower.org/Development/ROMHeader

This kind of discussion really would be better to have on smspower.org, as many users more knowledgable than me could chime in to correct and add information. My intention was not to offend you by suggesting to use the forums. If you'd like, go start a thread there, tell me you username and I'll go and post a copy of my answer above.
